"""Add game_user Association Table

Revision ID: 11b383ebf973
Revises: 4dd9f0534c3a
Create Date: 2025-05-24 19:55:57.302610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11b383ebf973'
down_revision = '4dd9f0534c3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
