"""Add User model

Revision ID: 932e50a748df
Revises: 2fa883df253f
Create Date: 2025-05-24 19:39:37.093229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '932e50a748df'
down_revision = '2fa883df253f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
